# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

bearerToken: Optional[str]
"""
Credential used to authenticate to the Smallstep API. May also be provided via the SMALLSTEP_API_TOKEN environment
variable. Use the Smallstep dashboard to manage API tokens. Ignored if a client certificate is set.
"""

clientCertificate: Optional[str]
"""
Get an API token with a client certificate key pair signed by your trusted root. Use the Smallstep dashboard to manage
trusted roots.
"""

