# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'ClientCertificate',
]

@pulumi.output_type
class ClientCertificate(dict):
    def __init__(__self__, *,
                 certificate: str,
                 private_key: str,
                 team_id: str):
        """
        :param str certificate: The PEM encoded certificate signed by your trusted root.
        :param str private_key: The PEM encoded private key
        :param str team_id: Your team's UUID
        """
        pulumi.set(__self__, "certificate", certificate)
        pulumi.set(__self__, "private_key", private_key)
        pulumi.set(__self__, "team_id", team_id)

    @property
    @pulumi.getter
    def certificate(self) -> str:
        """
        The PEM encoded certificate signed by your trusted root.
        """
        return pulumi.get(self, "certificate")

    @property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> str:
        """
        The PEM encoded private key
        """
        return pulumi.get(self, "private_key")

    @property
    @pulumi.getter(name="teamId")
    def team_id(self) -> str:
        """
        Your team's UUID
        """
        return pulumi.get(self, "team_id")


